name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      # Step 1: Checkout Code
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: firstname lastname, username, username@users.noreply.github.com
      - name: Commit metrics image
        uses: EndBug/add-and-commit@v9
        with:
          add: "metrics.plugin.starlists.languages.svg"
          message: "Update language metrics"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          push: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Metrics in README
        run: |
          echo "![Programming Languages](metrics.plugin.starlists.languages.svg)" >> README.md
          git add README.md
          git commit -m "Add languages metrics to README"
          git push
