name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome
      - name: Commit metrics image
        uses: EndBug/add-and-commit@v9
        with:
          add: "metrics.plugin.starlists.languages.svg"
          message: "Update language metrics"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          push: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Metrics in README
        run: |
          echo "![Programming Languages](metrics.plugin.starlists.languages.svg)" >> README.md
          git add README.md
          git commit -m "Add language metrics to README"
          git push
